### ISSUE TITLE
delete user already used

### ISSUE THREAD

**Issue by leibnitzfermat** [edmarlozada/mikrotik-fix-usertime-onbrownout#1]
Would it be possible to delete already used vouchers?
/ip hotspot user remove [find uptime=00:05:00 limit-uptime=00:05:00]
used this script but the time does not match

**Comment by edmarlozada** [comment]
your issue is outside the scope of my script.
however, to answer your question:
yes you can delete already used vouchers.
use this mikrotik script:
/ip hotspot user remove [find (uptime=limit-uptime)]

**Comment by edmarlozada** [comment]
> Would it be possible to delete already used vouchers? /ip hotspot user remove [find uptime=00:05:00 limit-uptime=00:05:00] used this script but the time does not match

your issue is outside the scope of my script.
however, to answer your question:
yes you can delete already used vouchers.
use this mikrotik script:
/ip hotspot user remove [find uptime=00:05:00 and limit-uptime=00:05:00]
@leibnitzfermat
